-- Create the database for MLflow if it doesn't exist.
-- The `\gexec` command executes the query generated by the SELECT statement.
SELECT 'CREATE DATABASE mlflow_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mlflow_db')\gexec

CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.policy (
    policy_no           VARCHAR(50)    NOT NULL PRIMARY KEY,
    cust_id             VARCHAR(50)    NOT NULL,        
    policytype          VARCHAR(50),
    pol_issue_date      DATE,
    pol_eff_date        DATE,
    pol_expiry_date     DATE,
    make                VARCHAR(50), 
    model               VARCHAR(50), 
    model_year          INT, 
    chassis_no          VARCHAR(50), 
    use_of_vehicle      VARCHAR(100),
    product             VARCHAR(100), 
    sum_insured         NUMERIC(15, 2), -- Use NUMERIC for currency
    premium             NUMERIC(15, 2), -- Use NUMERIC for currency
    deductable          INT 
);

CREATE TABLE IF NOT EXISTS demo.claim (
    claim_no                        VARCHAR(50)    NOT NULL PRIMARY KEY,
    policy_no                       VARCHAR(50)    NOT NULL,   
    claim_date                      DATE,           -- Use DATE type
    months_as_customer              INT,
    injury                          BIGINT,
    property                        BIGINT,
    vehicle                         BIGINT,
    total                           BIGINT,
    collision_type                  VARCHAR(50),
    number_of_vehicles_involved     INT, 
    driver_age                      INT,            -- Age is typically an integer
    insured_relationship            VARCHAR(50),
    license_issue_date              DATE,           -- Use DATE type
    incident_date                   DATE,           -- Use DATE type
    incident_hour                   INT,
    incident_type                   VARCHAR(50),
    incident_severity               VARCHAR(50),
    number_of_witnesses             INT, 
    suspicious_activity             BOOLEAN         -- Use BOOLEAN for true/false
);

CREATE TABLE IF NOT EXISTS demo.customer (
    customer_id INT NOT NULL PRIMARY KEY,
    date_of_birth DATE NULL,                        -- Use DATE type
    borough VARCHAR(100) NULL,
    neighborhood VARCHAR(150) NULL,
    zip_code VARCHAR(10) NULL,
    name VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS demo.user (
    user_id SERIAL PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(15) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE PUBLICATION dbz_publication FOR TABLE demo.policy, demo.claim, demo.customer;

-- 1. Add the column
ALTER TABLE demo.user 
ADD COLUMN customer_id INT;

-- 2. Add the foreign key constraint
ALTER TABLE demo.user
ADD CONSTRAINT fk_user_customer
FOREIGN KEY (customer_id) 
REFERENCES demo.customer(customer_id);